import { Edge, MarkerType, Node } from "@xyflow/react";

export const nodes: Node[] = [
  {
    id: "title",
    position: {
      x: 78,
      y: 81,
    },
    data: {
      label: "Client",
    },
    draggable: false,
    type: "title",
  },
  {
    id: "1",
    position: { x: 68, y: 89 },
    data: { color: "#3ea50b" },
    draggable: false,
    type: "coloredVerticalLine",
  },
  {
    id: "2",
    position: { x: 68, y: 152 },
    data: { color: "#3ea50b", height: 68 },
    draggable: false,
    type: "coloredVerticalLine",
  },
  {
    id: "3",
    position: { x: 68, y: 560 },
    data: { color: "#3ea50b", height: 68 },
    draggable: false,
    type: "coloredVerticalLine",
  },
  {
    id: "4",
    position: { x: 110, y: 149 },
    data: { label: "Send order information", width: 150 },
    draggable: false,
    type: "regularNode",
  },
  {
    id: "title2",
    position: {
      x: 310,
      y: 81,
    },
    data: {
      label: "Server",
    },
    draggable: false,
    type: "title",
  },
  {
    id: "2.1",
    position: { x: 300, y: 89 },
    data: { color: "#ff8f0e" },
    draggable: false,
    type: "coloredVerticalLine",
  },
  {
    id: "2.2",
    position: { x: 300, y: 152 },
    data: { color: "#ff8f0e", height: 68 },
    draggable: false,
    type: "coloredVerticalLine",
  },
  {
    id: "2.2.1",
    position: { x: 342, y: 149 },
    data: { label: "Create Checkout Session", width: 150 },
    draggable: false,
    type: "regularNode",
  },
  {
    id: "2.3",
    position: { x: 300, y: 275 },
    data: { color: "#ff8f0e", height: 68 },
    draggable: false,
    type: "coloredVerticalLine",
  },
  {
    id: "2.3.1",
    position: { x: 342, y: 273 },
    data: { label: "Return Checkout Session", width: 150 },
    draggable: false,
    type: "regularNode",
  },
  {
    id: "2.4",
    position: { x: 300, y: 401 },
    data: { color: "#ff8f0e", height: 68 },
    draggable: false,
    type: "coloredVerticalLine",
  },
  {
    id: "2.5",
    position: { x: 150, y: 568 },
    data: { label: "Customer returns to your application", width: 500 },
    draggable: false,
    type: "regularNode",
  },
  {
    id: "2.6",
    position: { x: 300, y: 690 },
    data: { color: "#ff8f0e", height: 68 },
    draggable: false,
    type: "coloredVerticalLine",
  },
  {
    id: "2.6.1",
    position: { x: 342, y: 698 },
    data: { label: "Handle fulfillment", width: 150 },
    draggable: false,
    type: "regularNode",
  },
  {
    id: "3.1",
    position: { x: 532, y: 89 },
    data: { color: "#0659bd" },
    draggable: false,
    type: "coloredVerticalLine",
  },
  {
    id: "title3",
    position: {
      x: 542,
      y: 81,
    },
    data: {
      label: "Stripe API",
    },
    draggable: false,
    type: "title",
  },
  {
    id: "3.2",
    position: { x: 532, y: 152 },
    data: { color: "#0659bd", height: 68 },
    draggable: false,
    type: "coloredVerticalLine",
  },
  {
    id: "3.3",
    position: { x: 532, y: 275 },
    data: { color: "#0659bd", height: 68 },
    draggable: false,
    type: "coloredVerticalLine",
  },
  {
    id: "3.4",
    position: { x: 408, y: 398 },
    data: { label: "Redirect customer to url from Checkout Session", width: 250 },
    draggable: false,
    type: "regularNode",
  },
  {
    id: "3.5",
    position: { x: 532, y: 690 },
    data: { color: "#0659bd", height: 68 },
    draggable: false,
    type: "coloredVerticalLine",
  },
  {
    id: "4.1",
    position: { x: 732, y: 89 },
    data: { color: "#635bff" },
    draggable: false,
    type: "coloredVerticalLine",
  },  
  {
    id: "title4",
    position: {
      x: 742,
      y: 81,
    },
    data: {
      label: "Stripe Checkout",
    },
    draggable: false,
    type: "title",
  },
  {
    id: "4.2",
    position: { x: 732, y: 400 },
    data: { color: "#635bff", height: 68 },
    draggable: false,
    type: "coloredVerticalLine",
  },
  {
    id: "4.3",
    position: { x: 732, y: 560 },
    data: { color: "#635bff", height: 68 },
    draggable: false,
    type: "coloredVerticalLine",
  },
  {
    id: "5.1",
    position: { x: 800, y: 480 },
    data: { label: "Customer completes payment", width: 155 },
    draggable: false,
    type: "regularNode",
  },
  
];

export const edges: Edge[] = [
  {
    id: "1-2",
    source: "1",
    target: "2",
    sourceHandle: "bottom",
    targetHandle: "top",
  },
  {
    id: "2-3",
    source: "2",
    target: "3",
    sourceHandle: "bottom",
    targetHandle: "top",
  },
  {
    id: "2-4",
    source: "2",
    target: "4",
    sourceHandle: "right",
    targetHandle: "left",
    markerEnd: {
      type: MarkerType.ArrowClosed,
      width: 20,
      height: 20,
    },
  },
  {
    id: "2.1-2.2",
    source: "2.1",
    target: "2.2",
    sourceHandle: "bottom",
    targetHandle: "top",
  },
  {
    id: "2.2-2.3",
    source: "2.2",
    target: "2.3",
    sourceHandle: "bottom",
    targetHandle: "top",
  },
  {
    id: "2.3-2.4",
    source: "2.3",
    target: "2.4",
    sourceHandle: "bottom",
    targetHandle: "top",
  },
  {
    id: "2.4-2.6",
    source: "2.4",
    target: "2.6",
    sourceHandle: "bottom",
    targetHandle: "top",
  },
  {
    id: "4-2.2",
    source: "4",
    target: "2.2",
    sourceHandle: "right",
    targetHandle: "left",
    markerEnd: {
      type: MarkerType.ArrowClosed,
      width: 20,
      height: 20,
    },
  },
  {
    id: "2.2-2.2.1",
    source: "2.2",
    target: "2.2.1",
    sourceHandle: "right",
    targetHandle: "left",
    markerEnd: {
      type: MarkerType.ArrowClosed,
      width: 20,
      height: 20,
    },
  },
  {
    id: "3.1-3.2",
    source: "3.1",
    target: "3.2",
    sourceHandle: "bottom",
    targetHandle: "top",
  },
  {
    id: "3.2-3.3",
    source: "3.2",
    target: "3.3",
    sourceHandle: "bottom",
    targetHandle: "top",
  },
  {
    id: "2.2.1-3.2",
    source: "2.2.1",
    target: "3.2",
    sourceHandle: "right",
    targetHandle: "left",
    markerEnd: {
      type: MarkerType.ArrowClosed,
      width: 20,
      height: 20,
    },
  },
  {
    id: "2.3.1-2.3",
    source: "2.3.1",
    target: "2.3",
    sourceHandle: "left",
    targetHandle: "right",
    markerEnd: {
      type: MarkerType.ArrowClosed,
      width: 20,
      height: 20,
    },
  },
  {
    id: "3.3-2.3.1",
    source: "3.3",
    target: "2.3.1",
    sourceHandle: "left",
    targetHandle: "right",
    markerEnd: {
      type: MarkerType.ArrowClosed,
      width: 20,
      height: 20,
    },
  },
  {
    id: "3.3-3.4",
    source: "3.3",
    target: "3.4",
    sourceHandle: "bottom",
    targetHandle: "top",
  },
  {
    id: "3.4-3.5",
    source: "3.4",
    target: "3.5",
    sourceHandle: "bottom",
    targetHandle: "top",
  },
  {
    id: "2.4-3.4",
    source: "2.4",
    target: "3.4",
    sourceHandle: "right",
    targetHandle: "left",
    markerEnd: {
      type: MarkerType.ArrowClosed,
      width: 20,
      height: 20,
    },
  },
  {
    id: "3.4-4.2",
    source: "3.4",
    target: "4.2",
    sourceHandle: "right",
    targetHandle: "left",
    markerEnd: {
      type: MarkerType.ArrowClosed,
      width: 20,
      height: 20,
    },
  },
  {
    id: "4.1-4.2",
    source: "4.1",
    target: "4.2",
    sourceHandle: "bottom",
    targetHandle: "top",
  },
  {
    id: "4.2-4.3",
    source: "4.2",
    target: "4.3",
    sourceHandle: "bottom",
    targetHandle: "top",
  },
  {
    id: "4.2-5.1",
    source: "4.2",
    target: "5.1",
    sourceHandle: "right",
    targetHandle: "top",
    type: "smoothstep",
    markerEnd: {
      type: MarkerType.ArrowClosed,
      width: 20,
      height: 20,
    },
  },
  {
    id: "5.1-4.3",
    source: "5.1",
    target: "4.3",
    sourceHandle: "bottom",
    targetHandle: "right",
    type: "smoothstep",
    markerEnd: {
      type: MarkerType.ArrowClosed,
      width: 20,
      height: 20,
    },
  },
  {
    id: "2.6.1-2.6",
    source: "2.6.1",
    target: "2.6",
    sourceHandle: "left",
    targetHandle: "right",
    markerEnd: {
      type: MarkerType.ArrowClosed,
      width: 20,
      height: 20,
    },
    style: {
      strokeDasharray: "10,10",
    }
  },
  {
    id: "3.5-2.6.1",
    source: "3.5",
    target: "2.6.1",
    sourceHandle: "left",
    targetHandle: "right",
    markerEnd: {
      type: MarkerType.ArrowClosed,
      width: 20,
      height: 20,
    },
    style: {
      strokeDasharray: "10,10",
    }
  },
  {
    id: "4.3-2.5",
    source: "4.3",
    target: "2.5",
    sourceHandle: "left",
    targetHandle: "right",
    markerEnd: {
      type: MarkerType.ArrowClosed,
      width: 20,
      height: 20,
    },
  },
  {
    id: "2.5-3",
    source: "2.5",
    target: "3",
    sourceHandle: "left",
    targetHandle: "right",
    markerEnd: {
      type: MarkerType.ArrowClosed,
      width: 20,
      height: 20,
    },
  },
];
